// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.27.0
// source: test.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTestCreateTest = "/api.test.service.v1.Test/CreateTest"

type TestHTTPServer interface {
	CreateTest(context.Context, *CreateTestRequest) (*CreateTestReply, error)
}

func RegisterTestHTTPServer(s *http.Server, srv TestHTTPServer) {
	r := s.Route("/")
	r.POST("/api/test/service/v1/test", _Test_CreateTest0_HTTP_Handler(srv))
}

func _Test_CreateTest0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTestCreateTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTest(ctx, req.(*CreateTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTestReply)
		return ctx.Result(200, reply)
	}
}

type TestHTTPClient interface {
	CreateTest(ctx context.Context, req *CreateTestRequest, opts ...http.CallOption) (rsp *CreateTestReply, err error)
}

type TestHTTPClientImpl struct {
	cc *http.Client
}

func NewTestHTTPClient(client *http.Client) TestHTTPClient {
	return &TestHTTPClientImpl{client}
}

func (c *TestHTTPClientImpl) CreateTest(ctx context.Context, in *CreateTestRequest, opts ...http.CallOption) (*CreateTestReply, error) {
	var out CreateTestReply
	pattern := "/api/test/service/v1/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTestCreateTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
