// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"framework-kratos/app/test/service/v1/internal/biz"
	"framework-kratos/app/test/service/v1/internal/conf"
	"framework-kratos/app/test/service/v1/internal/data"
	"framework-kratos/app/test/service/v1/internal/server"
	"framework-kratos/app/test/service/v1/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	testRepo := data.NewTestRepo(dataData, logger)
	testCase := biz.NewTestCase(testRepo, logger)
	testService := service.NewTestService(testCase, logger)
	grpcServer := server.NewGRPCServer(confServer, testService, logger)
	httpServer := server.NewHTTPServer(confServer, testService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
